import './globals.css'
import { Inter } from 'next/font/google'
import SidebarLayout from './components/SidebarLayout'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'IntelliGPT',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarLayout>
          {children}
        </SidebarLayout>
      </body>
    </html>
  )
}
